version: '3.7'
services:
  api:
    image: workshop/back-python
    networks:
      - web
    ports:
      - "5000:5000"
  web:
    image: workshop/quantique
    restart: always
    networks:
      - web
    ports:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=quantique"
      - "traefik.frontend.rule=Host:quantique.anthony-perruchas.fr"
    depends_on:
      - api
networks:
  web:
    external: true
